# Generated by Django 5.1.2 on 2024-10-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_url', models.URLField()),
                ('new_price', models.CharField(max_length=50)),
                ('old_price', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.CharField(blank=True, max_length=20, null=True)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
