# Generated by Django 5.1.2 on 2024-10-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('new_price', models.CharField(max_length=100)),
                ('old_price', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('ratings', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
